### ISSUE TITLE
compile issue: Cannot use CONFIG_LTO_CLANG: requires LLD

### ISSUE THREAD

**Issue by tpy2f0** [op5-q/kernel_oneplus_msm8998#2]
Hello
I just started learning kernel compilation, so I fork your kernel source code and use the clang tool at https://github.com/kdrag0n/proton-clang
this is my Compile command
#!/bin/bash
args="-j$(nproc –all) \
O=out \
ARCH=arm64 \
SUBARCH=arm64 \
CLANG_TRIPLE=aarch64-linux-gnu- \
CROSS_COMPILE=${HOME}/clang-proton/bin/aarch64-linux-gnu- \
CC=${HOME}/clang-proton/bin/clang \
CROSS_COMPILE_ARM32=${HOME}/clang-proton/bin/arm-linux-gnueabi-"
make ${args} oneplus5_defconfig
make ${args}

then
it failed as
VDSOA arch/arm64/kernel/vdso/sigreturn.o
VDSOL arch/arm64/kernel/vdso/vdso.so.dbg
VDSOSYM include/generated/vdso-offsets.h
Cannot use CONFIG_LTO_CLANG: requires LLD
make[1]: *** [/root/op5/Makefile:1161: prepare] Error 1
make[1]: Leaving directory ‘/root/op5/out’
make: *** [Makefile:152: sub-make] Error 2
root@vultr:~/op5#

Complete log as fllo
I just started learning kernel compilation, so I fork your kernel source code and use the clang tool at https://github.com/kdrag0n/proton-clang
this is my Compile command
#!/bin/bash
args="-j$(nproc –all) \
O=out \
ARCH=arm64 \
SUBARCH=arm64 \
CLANG_TRIPLE=aarch64-linux-gnu- \
CROSS_COMPILE=${HOME}/clang-proton/bin/aarch64-linux-gnu- \
CC=${HOME}/clang-proton/bin/clang \
CROSS_COMPILE_ARM32=${HOME}/clang-proton/bin/arm-linux-gnueabi-"
make ${args} oneplus5_defconfig
make ${args}

then
it failed as
VDSOA arch/arm64/kernel/vdso/sigreturn.o
VDSOL arch/arm64/kernel/vdso/vdso.so.dbg
VDSOSYM include/generated/vdso-offsets.h
Cannot use CONFIG_LTO_CLANG: requires LLD
make[1]: *** [/root/op5/Makefile:1161: prepare] Error 1
make[1]: Leaving directory ‘/root/op5/out’
make: *** [Makefile:152: sub-make] Error 2
root@vultr:~/op5#

Complete log as https://pastebin.com/p4Z3FNmq

Looking forward to your reply

**Comment by poad42** [comment]
Declare lld as part of your compile script. I always compile my kernel inline when building the ROM so the build system does it for me.

**Comment by tpy2f0** [comment]
> Declare lld as part of your compile script. I always compile my kernel inline when building the ROM so the build system does it for me.

Thank you very much for your reply，it works！Wish you all the best！
